# Generated by Django 2.1.7 on 2019-03-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubereatsapp', '0002_customer_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='restaurant_name',
        ),
    ]
